on: [push]

jobs:
  validate_openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate OpenAPI using Swagger CLI
        uses: mbowman100/swagger-validator-action@2.0
        with:
          files: spec.yaml

