name: Prepare I-D for Datatracker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Install kramdown-rfc
        run: gem install --no-document kramdown-rfc

      - name: Bump I-D version
        run: perl -pe 's/open-cloud-mesh-(\d+)/"open-cloud-mesh-" . sprintf("%02d", $1 + 1)/e' -i IETF-RFC.md || exit -1

      - name: Convert Markdown to XML and save output
        id: convert
        run: |
          result=$(kramdown-rfc IETF-RFC.md > IETF-RFC.xml 2> /tmp/result)
          echo "result<<EOF" >> $GITHUB_OUTPUT
          cat /tmp/result >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: rfc-md
          path: IETF-RFC.md

      - uses: actions/upload-artifact@v4
        with:
          name: rfc-xml
          path: IETF-RFC.xml

      # Create a PR to the repo with the results
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: rfc/gen-${{ github.sha }}
          base: develop
          add-paths: |
            IETF-RFC.md
            IETF-RFC.xml
          commit-message: 'CI: regenerate IETF-RFC.xml for Datatracker'
          signoff: true
          title: 'Regenerate IETF-RFC.xml'
          body: 'This autogenerated PR bumps the IETF version of the I-D and prepares the IETF-RFC.xml file for submission to the [IETF Datatracker](https://datatracker.ietf.org/submit).\n\nThe conversion produced the output below:\n```${{ steps.get_output.convert.result }}```'
          reviewers: |
            glpatcern
            MahdiBaghbani
            mickenordin
