name: Build RFC XML

on:
  push:
    paths: [IETF-RFC.md]
  workflow_dispatch:         

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Ruby setup
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Install kramdown-rfc
        run: gem install --no-document kramdown-rfc

      - name: Convert Markdown to XML
        run: kramdown-rfc IETF-RFC.md > IETF-RFC.xml

      - uses: actions/upload-artifact@v4
        with:
          name: rfc-xml
          path: IETF-RFC.xml

      # Commit the result back to the repo
      - uses: peter-evans/create-pull-request@v6
        with:
          branch: rfc/gen-${{ github.sha }}
          base: develop
          add-paths: |
            IETF-RFC.xml
          commit-message: 'CI: regenerate IETF-RFC.xml'
          signoff: true
          title: 'Regenerate IETF-RFC.xml'
          body: 'Automatic XML regeneration by CI'
          reviewers: |
            glpatcern
            michielbdejong
